name: 'get-changed-files'
description: ''
author: 'nanasi880'

branding:
  icon: 'file-plus'
  color: 'orange'

inputs:
  token:
    required: true
    default: ${{ github.token }}
    description: Github Token
  format:
    required: true
    default: 'space-delimited'
    description: "'space-delimited' or 'json'"

outputs:
  all:
    description: "all changed files"
  added:
    description: 'added files'
  modified:
    description: 'modified files'
  added_modified:
    description: 'added or modified files'
  removed:
    description: 'removed files'
  renamed:
    description: 'renamed files'

runs:
  using: node20
  main: dist/index.js
